return failure codes when various git commands fail

diff --git a/git b/git
--- a/git
+++ b/git
@@ -11,7 +11,7 @@ git_change_list() {
     git ls-files -m --exclude-standard
 }
 git_get_svn_branch() {
-    local branch=`git svn info | grep URL | cut -c6-` || return
+    local branch=`git svn info | grep URL | cut -c6-` || return 1
     if [[ "$branch" =~ '/trunk' ]]; then
         echo "trunk"
     elif [[ "$branch" =~ '/branches/' ]]; then
@@ -48,12 +48,12 @@ git_svn_dcommit() {
     fi
     local branch=`git_get_branch`
     echo commiting $branch
-    git svn rebase || { echo "failed to rebase"; return; }
-    git svn dcommit || { echo "dcommit failed"; return; }
+    git svn rebase || { echo "failed to rebase"; return 1; }
+    git svn dcommit || { echo "dcommit failed"; return 1; }
 
     if ! [[ "$branch" =~ "master" ]]; then
-        git_switch_to_master || return
-        git svn rebase
+        git_switch_to_master || return 1
+        git svn rebase || return 1
         read -p "Do you want to delete the branch ${branch}? y/N " -n1 delete
         echo
 
@@ -78,15 +78,15 @@ git_update_from_subversion() {
         git stash
     fi
     if ! [[ "$branch" =~ "master" ]]; then
-        git_switch_to_master || return
+        git_switch_to_master || return 1
     fi
 
-    git svn rebase || { echo "failed to rebase"; return; }
+    git svn rebase || { echo "failed to rebase"; return 1; }
 
     if ! [[ "$branch" =~ "master" ]]; then
         local master=`git_get_master_branch`
-        git checkout $branch || { echo "could not change to branch: $branch"; return; }
-        git rebase $master
+        git checkout $branch || { echo "could not change to branch: $branch"; return 1; }
+        git rebase $master || return 1
     fi
     if ! [ -z "$changes" ]; then
         git stash pop
@@ -96,7 +96,7 @@ alias gup=git_update_from_subversion
 
 git_diff_single_revision() {
     local revision=$(git svn find-rev r${1#r})
-    [ -z "$revision" ] && { echo "no such revision found"; return; }
+    [ -z "$revision" ] && { echo "no such revision found"; return 1; }
     git diff ${revision}^!
 }
 alias gdiff=git_diff_single_revision
