update boot2docker scripts for docker-machine

diff --git a/plugins/docker b/plugins/docker
--- a/plugins/docker
+++ b/plugins/docker
@@ -1,42 +1,59 @@
+VM=default
+DOCKER_MACHINE=/usr/local/bin/docker-machine
+VBOXMANAGE=/Applications/VirtualBox.app/Contents/MacOS/VBoxManage
+
 docker_env() {
     if docker_is_running; then
-        export DOCKER_IP=$(boot2docker ip 2> /dev/null)
-        export DOCKER_HOST=tcp://${DOCKER_IP}:2375
+        eval "$(docker-machine env --shell=bash $VM)"
     else
-        export DOCKER_IP=
-        export DOCKER_HOST=
+        for s in $(env | grep '^DOCKER_' | cut -d '=' -f1); do
+            unset $s
+        done
     fi
 }
 
-docker_start() {
-    /usr/local/bin/boot2docker up && docker_env
-    docker version
+__docker_create_machine() {
+    if ! $VBOXMANAGE showvminfo $VM > /dev/null; then
+        $DOCKER_MACHINE rm -f $VM > /dev/null
+        rm -rf ~/.docker/machine/machines/$VM
+        $DOCKER_MACHINE create -d virtualbox --virtualbox-memory 2048 --virtualbox-disk-size 204800 $VM
+    fi
+}
+
+__docker_start() {
+    __docker_create_machine
+    $DOCKER_MACHINE start $VM && docker_env
+    yes | $DOCKER_MACHINE regenerate-certs $VM
 }
 
 docker_stop() {
-    /usr/local/bin/boot2docker down && docker_env
+    $DOCKER_MACHINE stop $VM && docker_env
+}
+
+__docker_update_vm_time() {
+    $DOCKER_MACHINE ssh $VM sudo ntpclient -s -h pool.ntp.org > /dev/null || echo "failed to update time in virtual machine" >&2
 }
 
 docker_ensure() {
     if ! docker_is_running; then
-        docker_start
-        /usr/local/bin/boot2docker ssh sudo ntpclient -s -h pool.ntp.org > /dev/null
+        __docker_start
+        __docker_update_vm_time
     else
         docker_env
-        /usr/local/bin/boot2docker ssh sudo ntpclient -s -h pool.ntp.org > /dev/null
+        __docker_update_vm_time
     fi
 }
 
 docker_is_running() {
-    [ "running" == "$(boot2docker status 2> /dev/null)" ]
+    [ "Running" == "$($DOCKER_MACHINE status $VM 2> /dev/null)" ]
 }
 
 docker_kill_all() {
-    for s in $(docker ps | grep -v ^CONTAINER | awk '{print $1}'); do docker kill $s; done
+    docker kill $(docker ps -q)
 }
 
 docker_containers_rm_all() {
-    for s in $(docker ps -a | grep -v ^CONTAINER | awk '{print $1}'); do docker rm -fv $s; done
+    docker rm -fv $(docker ps -aq)
 }
 
 docker_containers_rm_exited() {
@@ -48,7 +65,7 @@ docker_images_rm_all() {
 }
 
 docker_images_rm_orphans() {
-    for s in $(docker images | grep '^<none>' | awk '{print $3}'); do docker rmi $s; done
+    docker rmi $(docker images -f "dangling=true" -q)
 }
 
 if docker_is_running; then
